# Generated by Django 5.0.4 on 2024-04-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_image',
            new_name='image',
        ),
    ]
